<%- if progress_topic = ENV['BLOCKS_BATCH_PROGRESS_TOPIC'] -%>
progress_notification:
  topic: <%= progress_topic %>
<%- end -%>

loggers:
- type: stdout
<%- if log_name = ENV['BLOCKS_BATCH_CLOUD_LOGGING_LOG_NAME'] -%>
- type: cloud_logging
  log_name: <%= log_name %>
<%- end -%>

sustainer:
  # delay:
  #   Delay message deadline for log jobs.
  #   It must be less than or equal to ACK_DEADLINE of subscription
  #   specified by BLOCKS_BATCH_PUBSUB_SUBSCRIPTION
  #   You can check ACK_DEADLINE by `gcloud beta pubsub subscriptions list`
  #   ACK_DEADLINE is set by `--ack-deadline` option for `gcloud beta pubsub subscriptions create`.
  delay: 600

  # interval
  #   The interval to send delay message. It must be lower than delay
  #   Default: 90% of delay
  interval: 540
