Style/Documentation:
  Enabled: false

LineLength:
  Max: 130

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Lint/AssignmentInCondition:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
