
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Gurpartap/logrus-stack"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  source = "https://github.com/cenkalti/backoff.git"

[[constraint]]
  name = "github.com/groovenauts/blocks-variable"

[[constraint]]
  branch = "fix/error_reporting"
  name = "github.com/knq/sdhook"
  source = "https://github.com/groovenauts/sdhook.git"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "~1.1.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  source = "https://github.com/sirupsen/logrus.git"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "github.com/urfave/cli"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "google.golang.org/api"
